name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          libopencv-dev \
          libeigen3-dev \
          libglfw3-dev \
          libglm-dev \
          cmake \
          build-essential \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          libxrandr-dev \
          libgl1-mesa-dev
          
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        ls -lh TheEye
        file TheEye

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TheEye-Linux
        path: build/TheEye
        retention-days: 7
